### ISSUE TITLE
Patient age?

### ISSUE THREAD

**Issue by lwaldsc** [colinxfleming/clinic_finder#9]
Do we want to add a filter for state laws regarding minor patients? (parental consent, will not see patient, no laws)

**Comment by colinxfleming** [comment]
Can you give me a sense of what the impact is like there when case
managing? My sense is that the core stuff we have to think about when cming
is geo, cash, and how many weeks the clinic goes to, but if this is
something like half our patients experience then let's push it up.

I think if it's like a front and center thing then we work it into the gold
medal of MVP, otherwise do it as part of incremental improvements.

**Comment by lwaldsc** [comment]
My thought on this is if it is going country-wide rather than just DCAF's
domain it might be useful for other funds.

**Comment by colinxfleming** [comment]
Let's hold on generalizing for now. I want to have a proof of concept with a limited data model in place before we start worrying about state laws, though we should keep this in mind as we continue to develop.
